name: Flutter Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        
    - name: Fix Android Gradle
      run: |
        # Check and regenerate Android files if needed
        if [ ! -f "android/gradlew" ]; then
          echo "Regenerating Android project files..."
          rm -rf android
          flutter create --platforms android .
        fi
        
        # Verify gradlew exists and is executable
        ls -la android/gradlew
        chmod +x android/gradlew
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: build/app/outputs/apk/release/app-release.apk
